In [38]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [39]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target, test_size=.03)

In [29]:
Lr = LogisticRegression(max_iter=30)
Lr.fit(X_train, y_train)
Lr.score(X_test, y_test)

/Users/davidjohns/opt/miniconda3/envs/reu/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9629629629629629

In [30]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

1.0

In [31]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

1.0

In [34]:
from sklearn.model_selection import  KFold
kf = KFold(n_splits=3)

In [35]:
for train_index, test_idex in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_idex)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [40]:
def get_score(model, X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [59]:
from sklearn.model_selection import StratifiedGroupKFold
folds = StratifiedGroupKFold(n_splits = 3)

In [51]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_test,X_train,y_test,y_train =  digits.data[train_index], digits.data[test_index], \
       digits.target[train_index],digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(solver='lbfgs',max_iter=1000), X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(), X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train,X_test,y_train,y_test))



/Users/davidjohns/opt/miniconda3/envs/reu/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/davidjohns/opt/miniconda3/envs/reu/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable

In [55]:
print("Logistic regression scores: ",scores_l,"\n","-"*100)
print("Support Vector Classification scores: ",scores_svm,"\n","-"*100)
print("Random Forest scores: ",scores_rf,"\n","-"*100)



Logistic regression scores:  [0.9315525876460768, 0.8939899833055092, 0.8797996661101837] 
 ----------------------------------------------------------------------------------------------------
Support Vector Classification scores:  [0.9499165275459098, 0.9223706176961602, 0.9265442404006677] 
 ----------------------------------------------------------------------------------------------------
Random Forest scores:  [0.9106844741235393, 0.8998330550918197, 0.8998330550918197] 
 ----------------------------------------------------------------------------------------------------


In [56]:
from sklearn.model_selection import cross_val_score


In [ ]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

In [62]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [65]:
cross_val_score(RandomForestClassifier(n_estimators=100), digits.data, digits.target)

array([0.93333333, 0.93333333, 0.95821727, 0.96657382, 0.9275766 ])